name: Maven Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      jar_name: ${{ steps.jar_name.outputs.jar_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build com Maven
      run: mvn -B package -DskipTests --file pom.xml
    - name: Criar diretório para o JAR
      run: mkdir -p ./jar-upload
    - name: Copiar JAR para pasta temporária
      run: cp ./target/catalogodepecas.jar ./jar-upload/
    - name: Definir nome do JAR
      id: jar_name
      run: echo "::set-output name=jar_name::catalogodepecas"
    - name: Enviar JAR via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.HOST }}
        username: ${{ secrets.USUARIOCPANEL }}
        password: ${{ secrets.SENHACPANEL }}
        local-dir: ./jar-upload/
        server-dir: ~/appservers/standalone/
    - name: Instalar dependências SSH
      run: sudo apt-get install -y openssh-client sshpass expect
    - name: Parar aplicação Spring Boot
      env:
        USUARIOCPANEL: ${{ secrets.USUARIOCPANEL }}
        HOST: ${{ secrets.HOST }}
        SENHACPANEL: ${{ secrets.SENHACPANEL }}
      run: |
        expect -c "
        set timeout 15
        spawn ssh -o StrictHostKeyChecking=no $USUARIOCPANEL@$HOST
        expect \"password:\"
        send \"$SENHACPANEL\\r\"
        expect \"$ \"
        send \"bash appservers/tmp/curriculo.sh stop\\r\"
        expect \"$ \"
        send \"exit\\r\"
        expect eof
        "
    - name: Iniciar aplicação Spring Boot
      env:
        USUARIOCPANEL: ${{ secrets.USUARIOCPANEL }}
        HOST: ${{ secrets.HOST }}
        SENHACPANEL: ${{ secrets.SENHACPANEL }}
      run: |
        expect -c "
        set timeout 15
        spawn ssh -o StrictHostKeyChecking=no $USUARIOCPANEL@$HOST
        expect \"password:\"
        send \"$SENHACPANEL\\r\"
        expect \"$ \"
        send \"bash appservers/tmp/curriculo.sh start\\r\"
        expect \"$ \"
        send \"exit\\r\"
        expect eof
        "
